# Generated by Django 3.2.23 on 2024-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_alter_login1_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='usertype',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
