# Generated by Django 3.2.23 on 2024-01-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_alter_login1_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='login1',
            name='agency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.agency'),
        ),
        migrations.AddField(
            model_name='login1',
            name='std_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.student'),
        ),
    ]
