# Generated by Django 3.2.23 on 2024-01-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_auto_20240102_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login1',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='login1',
            name='std_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.login1'),
        ),
        migrations.AddField(
            model_name='student',
            name='login_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportal.login1'),
        ),
        migrations.AlterField(
            model_name='login1',
            name='usertype',
            field=models.IntegerField(null=True),
        ),
    ]
