# Generated by Django 3.2.23 on 2024-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
