# Generated by Django 3.2.23 on 2024-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_auto_20240119_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
