# Generated by Django 3.2.23 on 2024-01-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_agency_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='message',
        ),
    ]
