# Generated by Django 5.0.1 on 2024-01-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0011_remove_application_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
