# Generated by Django 5.0.1 on 2024-02-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0012_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login1',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
